### ISSUE TITLE
Task: Create a GPT-4 endpoint

### ISSUE THREAD

**Issue by ReinderVosDeWael** [cmi-dair/ctk-api#2]
### Description

The frontend should be able to request GPT-4 processing of a clinical report.

### Tasks

- [ ] Create a POST endpoint /summarization/openai
  - [ ] This endpoint should take the following inputs:
    - [ ] Text to anonymize. 
  - [ ] This endpoint should have the following things set by environment variables:
    - [ ] Model name.
    - [ ] OpenAI API key
  - [ ] This endpoint should have the following things hard-coded:
    - [ ] System message. 
  - [ ] This endpoint should log every request.
