### ISSUE TITLE
Task: Save all openAI inputs / responses to ElasticSearch

### ISSUE THREAD

**Issue by ReinderVosDeWael** [cmi-dair/ctk-api#7]
### Description

We want to be able to save all inputs / responses relating to OpenAI for caching and auditing purposes. To that end, we will use an ElasticSearch. 

### Tasks

- [ ] Implement ElasticSearch CRUD operations.
- [ ] Add ElasticSearch creation operations to all OpenAI requests for the input (before request is made!) and response.
- [ ] Check before sending data to OpenAI if this exact request has already been made. If yes, send cached response.
